### ISSUE TITLE
glib-3.x

### ISSUE THREAD

**Issue by fAntel** [mono/gkeyfile-sharp#2]
Hello. You plan to update gkeyfile-sharp to work with glib 3.x version?

**Comment by bl8** [comment]
Hi,

The gkeyfile-sharp code was only created as a stop-gap, as gtk-sharp 2.12.x doesn't provide any bindings for the GKeyFile API.
The version of gtk-sharp which binds GTK+ 3.x and GLib 2.28 now provides this API (in git master at https://github.com/mono/gtk-sharp/ and in the 2.99.x beta releases).

So updating gkeyfile-sharp does not seem useful, so there's no plan to do it.
